subscribers:

  camera_reading:
    topic: /typhoon_h480_2/cgo3_camera/image_raw
    queue_size: 1

actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector:
    topic: /uav_2/darknet_ros/found_object
    queue_size: 1
    latch: false

  bounding_boxes:
    topic: /uav_2/darknet_ros/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /uav_2/darknet_ros/detection_image
    queue_size: 1
    latch: true

image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
